export const data = [
    { occupation: "Agricultural\nlaborers", value: 98400, category: "Agriculture and\nForestry" },
    { occupation: "Farmers and\nplanters", value: 63012, category: "Agriculture and\nForestry" },
    { occupation: "Laborers", value: 29723, category: "Manual Labor and\nConstruction" },
    { occupation: "Steam railway\nemployees", value: 7440, category: "Transportation\nand Services" },
    { occupation: "Servants", value: 7000, category: "Personal and\nDomestic Services" },
    { occupation: "Draymen", value: 4390, category: "Transportation\nand Services" },
    { occupation: "Carpenters and\njoiners", value: 3781, category: "Manual Labor and\nConstruction" },
    { occupation: "Saw and planing\nmill employees", value: 2471, category: "Manual Labor and\nConstruction" },
    { occupation: "Messengers", value: 1970, category: "Transportation\nand Services" },
    { occupation: "Wood choppers", value: 1399, category: "Agriculture and\nForestry" },
    { occupation: "Blacksmiths and\nwheelwrights", value: 1328, category: "Manual Labor and\nConstruction" },
    { occupation: "Clergymen", value: 1277, category: "Professionals\nand Trade" },
    { occupation: "Masons", value: 1243, category: "Manual Labor and\nConstruction" },
    { occupation: "Brick-makers\nand potters", value: 1243, category: "Manual Labor and\nConstruction" },
    { occupation: "Others", value: 899, category: "Personal and\nDomestic Services" },
    { occupation: "Others", value: 837, category: "Professionals\nand Trade" },
    { occupation: "Others", value: 676, category: "Manual Labor and\nConstruction" },
    { occupation: "Others", value: 632, category: "Manual Labor and\nConstruction" },
    { occupation: "Others", value: 620, category: "Professionals\nand Trade" },
    { occupation: "Others", value: 620, category: "Transportation\nand Services" },
    { occupation: "Others", value: 520, category: "Professionals\nand Trade" },
    { occupation: "Others", value: 519, category: "Agriculture and\nForestry" },
];